config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/dashboard', to: 'dashboard#index'
  get '/conditions-dashboard', to: 'conditions_dashboard#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/trips-dashboard', to: 'trips_dashboard#index'
  get '/stations-dashboard', to: 'stations_dashboard#index'

  resources :stations, only: [:index, :show], param: :slug

  resources :trips, only: [:index, :show]

  resources :conditions, only: [:index, :show]

  get '/cart', to: 'carts#index'
  post '/cart', to: 'carts#create'
  patch '/cart', to: 'carts#update'
  delete '/cart', to: 'carts#destroy'

  resources :users, only: [:new, :create, :edit, :update]

  resources :orders, only: [:create, :show]

  get '/bike-shop', to: 'items#index'
  resources :items, only: [:show]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    get '/bike-shop', to: 'items#index'
    resources :trips, only: [:edit, :destroy, :new, :create, :update]
    resources :conditions, only: [:edit, :destroy, :new, :create, :update]
    resources :stations, only: [:edit, :update, :destroy, :create, :new], param: :slug
    resources :items, only: [:new, :create, :edit, :update]
    resources :orders, only: [:update, :show]
  end
end

app/models/station.rb
class Station < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates_presence_of :dock_count,
                        :city,
                        :installation_date
  before_save :generate_slug
  has_many :start_trips, foreign_key: 'start_station_id', class_name: "Trip", dependent: :destroy
  has_many :end_trips, foreign_key: 'end_station_id', class_name: "Trip", dependent: :destroy

  def self.total_stations
    count(:id)
  end

  def self.avg_number_bikes
    average(:dock_count).round(2)
  end

  def self.most_bikes
    where(dock_count: (Station.maximum(:dock_count)))
  end

  def self.least_bikes
    where(dock_count: (Station.minimum(:dock_count)))
  end

  def self.newest
    where(installation_date: (Station.maximum(:installation_date))).limit(1).first
  end

  def self.oldest
    where(installation_date: (Station.minimum(:installation_date))).limit(1).first
  end

  def to_param
    slug
  end

  def show_data
    {
    ride_count_started: ride_count("started"),
    ride_count_ended: ride_count("ended"),
    destination_station: [destination_station.name, destination_station.station_count],
    origination_station: [origination_station.name, origination_station.station_count],
    most_trips: most_trips,
    top_zip_code: top_zips,
    top_bike: top_bike
    }
  end

  def ride_count(point)
    if point == "started"
      start_trips.where(start_station_id: id).count
    elsif point == "ended"
      end_trips.where(end_station_id: id).count
    end
  end

  def destination_station
    Station.select("stations.*, count(trips.end_station_id) as station_count")
      .where("trips.start_station_id = ?", id)
      .joins("join trips on trips.start_station_id = stations.id")
      .order("station_count desc")
      .limit(1)
      .group("trips.end_station_id, stations.id")
      .first
  end

  def origination_station
    Station.select("stations.*, count(trips.start_station_id) as station_count")
      .where("trips.end_station_id = ?", id)
      .joins("join trips on trips.end_station_id = stations.id")
      .order("station_count desc")
      .limit(1)
      .group("trips.start_station_id, stations.id")
      .first
  end

  def most_trips
    start_trips.order("count_id desc").limit(1).group(:start_date).count(:id)
  end

  def top_zips
    start_trips.order("count_id desc").limit(1).group(:zip_code).count(:id)
  end

  def top_bike
    start_trips.order("count_id desc").limit(1).group(:bike_id).count(:id)
  end

  private
    def generate_slug
      self.slug = name.parameterize
    end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController
  def new
    @station = Station.new()
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:success] = "Station #{@station.name} has been successfully created!"
      redirect_to station_path(@station)
    else
      flash[:failure] = "Your station was not saved. Please try again."
      render :new
    end
  end

  def edit
    @station = Station.find_by_slug(params[:slug])
  end

  def update
    @station = Station.find_by_slug(params[:slug])
    if @station.update(station_params)
      flash[:success] = "Your changes to #{@station.name} have been saved."
      redirect_to station_path(@station)
    else
      flash[:failure] = "Could not save changes."
      render :edit
    end
  end

  def destroy
    @station = Station.find_by_slug(params[:slug])
    if @station.destroy
      flash[:success] = "You have succesfully deleted Station #{@station.name}."
    else
      flash[:failure] = "Station #{@station.name} could not be deleted."
    end
    redirect_to stations_path
  end

  private
    def station_params
      params.require(:station).permit(:name, :dock_count, :city, :installation_date)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

  def index
    @stations = Station.all
  end

  def show
    @station = Station.find_by(slug: params[:slug])
    @show_data = @station.show_data if @station.start_trips.first && @station.end_trips.first
  end
end

app/views/stations/dashboard.html.erb
Total count of stations- Station.all.count
  SQL: SELECT count(*) FROM stations;
Average bikes available per station - Station.average(:dock_count)
  SQL: SELECT average(dock_count) FROM stations;
Most bikes available at a station - Station.maximum(:dock_count)
  SQL: SELECT max(dock_count) FROM stations;
Stations where the most bikes are available - Station.where(dock_count: Station.maximum(:dock_count))
  SQL: SELECT * FROM stations WHERE dock_count = (SELECT MAX(dock_count) FROM stations);
Fewest bikes available at a station - Station.minimum(:dock_count)
  SQL SELECT min(dock_count) FROM stations;
Stations where the fewest bikes are available - Station.where(dock_count: Station.minimum(:dock_count))
  SQL: SELECT * FROM stations WHERE dock_count = (SELECT MIN(dock_count) FROM stations);
Most recently installed station -

The oldest station -

*** use something like this to dry up your code
def get_stations(param)
  Station.where(dock_count(: Station.method(param).call("cock_count"))
end
***

app/views/stations/index.html.erb
<h1 class='text-center'>Station Index</h1>

<% if current_admin? %>
  <%= link_to "Add New Station", new_admin_station_path, class: 'btn btn-secondary text-center' %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Dock Count</th>
      <th scope="col">City</th>
      <th scope="col">Installation Date</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody class='stations'>
    <% @stations.each do |station| %>
    <tr>
      <div id="station-<%= station.id %>">
      <th scope="row"><%= station.id %></th>
      <td><%= station.name %></td>
      <td><%= station.dock_count %></td>
      <td><%= station.city %></td>
      <td><%= station.installation_date %></td>
      <td>
        <%= link_to "View this Station", station_path(station), class: "btn btn-info" %>
        <% if current_admin? %>
          <%= link_to "Edit", edit_admin_station_path(station), class: 'btn btn-warning' %>
          <%= link_to "Delete", admin_station_path(station), method: :delete, class: 'btn btn-danger',
            data: {confirm: "Are you sure you want to delete #{station.name}?"} %>
        <% end %>
      </td>
      <div>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stations/show.html.erb
<h1 class='text-center'><%= @station.name %> Station</h1>
<%= link_to "Back to All Stations", stations_path, class: 'text-center'%>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Dock Count</th>
      <th scope="col">City</th>
      <th scope="col">Installation Date</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <div id="station-attributes">
      <th scope="row"><%= @station.id %></th>
        <td><%= @station.name %></td>
        <td><%= @station.dock_count %></td>
        <td><%= @station.city %></td>
        <td><%= @station.installation_date %></td>
      <% if current_admin? %>
        <td><%= link_to "Edit", edit_admin_station_path(@station), class: "btn btn-warning" %></td>
        <td><%= link_to "Delete", admin_station_path(@station), method: :delete, class: "btn btn-danger",
          data: {confirm: "Are you sure you want to delete #{@station.name}?"} %></td>
      <% end %>
    </div>
    </tr>
  </tbody>
</table>

<% if current_user %>
  <% if @station.start_trips.first && @station.end_trips.first %>

  <h3>Station Information</h3>
    <ul class='list-group'>
      <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-info">
        Number of rides started here:  <%= @show_data[:ride_count_started] %>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Number of rides ended here: <%= @show_data[:ride_count_ended] %>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-info">
        Most popular Destination Station: <%= @show_data[:destination_station][0] %> with <%= @show_data[:destination_station][1] %> arrivals
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Most popular Origination Station: <%= @show_data[:origination_station][0] %> with <%= @show_data[:origination_station][1] %> departures
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-info">
        Date of most trips: <%= @show_data[:most_trips].keys.first.in_time_zone("MST").strftime("%m/%d/%Y") %> with <%= @show_data[:most_trips].values.first %> rides
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Most frequent rider zip code: <%= @show_data[:top_zip_code].keys.first %> with <%= @show_data[:top_zip_code].values.first %> rides
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-info">
        Most used bike: <%= @show_data[:top_bike].keys.first %> (id) with <%= @show_data[:top_bike].values.first %> rides
      </li>
    </ul>
  <% else %>
    <p>Station has no data yet. Nothing to see here!</p>
  <% end %>
<% end %>