config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/dashboard', to: 'dashboard#index'
  get '/conditions-dashboard', to: 'conditions_dashboard#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/trips-dashboard', to: 'trips_dashboard#index'
  get '/stations-dashboard', to: 'stations_dashboard#index'

  resources :stations, only: [:index, :show], param: :slug

  resources :trips, only: [:index, :show]

  resources :conditions, only: [:index, :show]

  get '/cart', to: 'carts#index'
  post '/cart', to: 'carts#create'
  patch '/cart', to: 'carts#update'
  delete '/cart', to: 'carts#destroy'

  resources :users, only: [:new, :create, :edit, :update]

  resources :orders, only: [:create, :show]

  get '/bike-shop', to: 'items#index'
  resources :items, only: [:show]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    get '/bike-shop', to: 'items#index'
    resources :trips, only: [:edit, :destroy, :new, :create, :update]
    resources :conditions, only: [:edit, :destroy, :new, :create, :update]
    resources :stations, only: [:edit, :update, :destroy, :create, :new], param: :slug
    resources :items, only: [:new, :create, :edit, :update]
    resources :orders, only: [:update, :show]
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    if params[:sort]
      @orders = Order.filter_status(params[:sort])
    else
      @orders = Order.all
    end
      @status = Order.status_total
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_user

  def index
    @orders = Order.where(user_id: current_user.id)
  end
end

app/views/admin/dashboard/index.html.erb
<h1 class='text-center'>Welcome <%= current_user.username %>!</h1>

<h3>Your info: </h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Address</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <div id="user-<%= current_user.id %>">
        <td><%= current_user.first_name %></td>
        <td><%= current_user.last_name %></td>
        <td><%= current_user.address %></td>
        <td><%= current_user.email %></td>
        <td><%= link_to "Edit my account info", edit_user_path(current_user), class: 'btn btn-info' %></td>
        <td><%= link_to "View all Items in Bike Shop", admin_bike_shop_path, class: 'btn btn-info' %></td>
      </div>
    </tr>
  </tbody>
</table>

<br/>

<h2>Orders</h2>

<ul>
  <li>Ordered: <%= @status["ordered"] %></li>
  <li>Paid: <%= @status["paid"] %></li>
  <li>Completed: <%= @status["completed"] %></li>
  <li>Cancelled: <%= @status["cancelled"] %></li>
</ul>

<p id='status-filter'>Filters: <%= link_to "Cancelled", admin_dashboard_path(sort: "cancelled"), class: 'btn' %> |
  <%= link_to "Ordered", admin_dashboard_path(sort: "ordered"), class: 'btn' %> |
  <%= link_to "Paid", admin_dashboard_path(sort: "paid"), class: 'btn' %>|
  <%= link_to "Completed", admin_dashboard_path(sort: "completed"), class: 'btn' %>|
  <%= link_to "No Filter", admin_dashboard_path, class: 'btn' %></p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Order Number</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody class='orders'>
    <% @orders.each do |order| %>
    <div id="order-<%= order.id %>">
    <tr>
      <td><%= link_to "Order #{order.id}", admin_order_path(order) %></td>
      <td><%= order.status.capitalize %></td>
      <td><%= link_to "Cancel", admin_order_path(order, status: "cancelled"), method: :patch, class: 'btn btn-danger' if ["paid", "ordered"].include? order.status %></td>
      <td><%= link_to "Mark as Paid", admin_order_path(order, status: "paid"), method: :patch, class: 'btn btn-success' if order.status == "ordered" %></td>
      <td><%= link_to "Mark as Completed", admin_order_path(order, status: "completed"), method: :patch, class: 'btn btn-info' if order.status == "paid" %></td>
    </tr>
  </div>
  <% end %>
  </tbody>
</table>