config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/dashboard', to: 'dashboard#index'
  get '/conditions-dashboard', to: 'conditions_dashboard#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/trips-dashboard', to: 'trips_dashboard#index'
  get '/stations-dashboard', to: 'stations_dashboard#index'

  resources :stations, only: [:index, :show], param: :slug

  resources :trips, only: [:index, :show]

  resources :conditions, only: [:index, :show]

  get '/cart', to: 'carts#index'
  post '/cart', to: 'carts#create'
  patch '/cart', to: 'carts#update'
  delete '/cart', to: 'carts#destroy'

  resources :users, only: [:new, :create, :edit, :update]

  resources :orders, only: [:create, :show]

  get '/bike-shop', to: 'items#index'
  resources :items, only: [:show]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    get '/bike-shop', to: 'items#index'
    resources :trips, only: [:edit, :destroy, :new, :create, :update]
    resources :conditions, only: [:edit, :destroy, :new, :create, :update]
    resources :stations, only: [:edit, :update, :destroy, :create, :new], param: :slug
    resources :items, only: [:new, :create, :edit, :update]
    resources :orders, only: [:update, :show]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.erb
<body id='welcome-page'>

  <h1 class='text-center'>Welcome to Bike Share and Shop!</h1>

<% if current_user %>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to "Stations Dashboard", stations_dashboard_path %></li>
    <li class="list-group-item"><%= link_to "Conditions Dashboard", conditions_dashboard_path %></li>
    <li class="list-group-item"><%= link_to "Trips Dashboard", trips_dashboard_path %></li>
  </ul>
<% end %>

</body>