config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/dashboard', to: 'dashboard#index'
  get '/conditions-dashboard', to: 'conditions_dashboard#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/trips-dashboard', to: 'trips_dashboard#index'
  get '/stations-dashboard', to: 'stations_dashboard#index'

  resources :stations, only: [:index, :show], param: :slug

  resources :trips, only: [:index, :show]

  resources :conditions, only: [:index, :show]

  get '/cart', to: 'carts#index'
  post '/cart', to: 'carts#create'
  patch '/cart', to: 'carts#update'
  delete '/cart', to: 'carts#destroy'

  resources :users, only: [:new, :create, :edit, :update]

  resources :orders, only: [:create, :show]

  get '/bike-shop', to: 'items#index'
  resources :items, only: [:show]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    get '/bike-shop', to: 'items#index'
    resources :trips, only: [:edit, :destroy, :new, :create, :update]
    resources :conditions, only: [:edit, :destroy, :new, :create, :update]
    resources :stations, only: [:edit, :update, :destroy, :create, :new], param: :slug
    resources :items, only: [:new, :create, :edit, :update]
    resources :orders, only: [:update, :show]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 },
            presence: true
  validates_presence_of :description
  validates_presence_of :status
  enum status: %w(active retired)
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new()
  end

  def create
    @item = Item.create(item_params)
    if @item.image == ""
      @item.image = "trail_bike.jpg"
    end
    if @item.save
      flash[:success] = "Item #{@item.title} has been successfully created!"
      redirect_to item_path(@item)
    else
      flash[:failure] = "Your item was not saved. Please try again."
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "#{@item.title} has been updated."
      redirect_to item_path(@item)
    else
      flash[:failure] = 'Could not update item. Please try again.'
      render :edit
    end
  end

  private
    def item_params
      params.require(:item).permit(:title, :price, :description, :image)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/views/items/index.html.erb
<h1 class='text-center'>Items available in the Bike Shop!</h1>
<div class="container-fluid">
  <div class="row">
    <% @items.each do |item| %>
      <div class="col-sm-6 col-lg-3 py-2 item">
        <div class ='card' id="item-<%= item.id %>">
          <%= image_tag(item.image, class: "card-img-top", alt: "Bike picture") %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to item.title, item_path(item) %></h5>
          <p class="card-text">Price: <%= number_to_currency(item.price) %></p>
          <p class="card-text"><%= item.description %></p>
        </div>
          <% if item.status == "active" %>
            <%= button_to "Add to Cart", cart_path(item_id: item.id) %>
          <% else %>
            <p style='color: red'>Item Retired</p>
          <% end %>
          <% if current_admin? %>
            <%= link_to "Edit Item", edit_admin_item_path(item), class: 'btn btn-secondary text-center' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>


<div class="card text-white bg-success mb-3" style="width: 18rem;">
  <%= image_tag(@item.image, class: "card-img-top", alt: "Bike picture") %>
  <div class="card-body">
    <p class="card-text">Price: <%= number_to_currency(@item.price) %></p>
    <p class="card-text"><%= @item.description %></p>
  </div>
  <% if @item.status == "active" %>
    <%= button_to "Add to Cart", cart_path(item_id: @item.id), class: 'text-center' %>
  <% else %>
    <p style='color: red'>Item Retired</p>
  <% end %>
  </div>
</div>

<%= link_to "Back to Bike Shop", bike_shop_path, class: 'btn btn-secondary' %>